import { Check, ChevronDown, Cloud, CloudCog, GitBranch, LoaderCircle, Plus, Server, ShieldAlert, X } from 'lucide-react';
import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getListConnectionActionsQueryKey, getListConnectionsQueryKey, useApproveConnectionAction, useCreateConnectionAction, useListConnectionActions, useListConnections, useRejectConnectionAction } from '@workspace/api-client-react';
import { ConsoleShell, EmptyState, PageIntro, QueryState, SectionLabel, StatusPill } from '@/components/console-shell';

const icons: Record<string, typeof GitBranch> = { github: GitBranch, supabase: Server, cloudflare: Cloud };
const formatDate = (value: string) => new Intl.DateTimeFormat('ar', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value));

export default function ConnectionsPage() {
  const connections = useListConnections();
  const actions = useListConnectionActions();
  const createAction = useCreateConnectionAction();
  const approve = useApproveConnectionAction();
  const reject = useRejectConnectionAction();
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [provider, setProvider] = useState('github');
  const [action, setAction] = useState('طلب تغيير');
  const [target, setTarget] = useState('');
  const [description, setDescription] = useState('');
  const refresh = () => { queryClient.invalidateQueries({ queryKey: getListConnectionActionsQueryKey() }); queryClient.invalidateQueries({ queryKey: getListConnectionsQueryKey() }); };
  const submit = () => { if (!target.trim() || !description.trim()) return; createAction.mutate({ data: { provider, action, target: target.trim(), description: description.trim() } }, { onSuccess: () => { setTarget(''); setDescription(''); setShowForm(false); refresh(); } }); };
  const connectionList = connections.data ?? [];
  const actionList = actions.data ?? [];
  return <ConsoleShell>
    <div className="console-rise">
      <PageIntro eyebrow="الاتصالات / ٠٤" title="الصلاحيات واضحة. القرار لك." description="كل اتصال يعرض قدراته وحدوده. يمكنك تجهيز طلب تغيير، لكن التنفيذ الخارجي يبقى معلقاً حتى يوافق المالك." action={<button onClick={() => setShowForm(!showForm)} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-bold text-primary-foreground" data-testid="button-new-connection-action"><Plus size={16} /> طلب تغيير جديد</button>} />
      {showForm && <div className="mb-7 rounded-2xl border border-accent/50 bg-accent/10 p-5 sm:p-6" data-testid="form-connection-action"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">SUPERVISED CHANGE REQUEST</p><h2 className="mt-1 font-display text-lg font-bold">حضّر طلباً للموافقة</h2></div><button onClick={() => setShowForm(false)} className="rounded-lg p-2 hover:bg-accent/20" data-testid="button-close-connection-form"><X size={17} /></button></div><div className="grid gap-3 sm:grid-cols-3"><select value={provider} onChange={(event) => setProvider(event.target.value)} className="rounded-xl border border-input bg-background px-3 py-3 text-xs outline-none" data-testid="select-action-provider"><option value="github">GitHub</option><option value="supabase">Supabase</option><option value="cloudflare">Cloudflare</option></select><input value={action} onChange={(event) => setAction(event.target.value)} placeholder="نوع الإجراء" className="rounded-xl border border-input bg-background px-3 py-3 text-xs outline-none" data-testid="input-action-type" /><input value={target} onChange={(event) => setTarget(event.target.value)} placeholder="الهدف: branch / project / zone" className="rounded-xl border border-input bg-background px-3 py-3 text-xs outline-none ltr" data-testid="input-action-target" /></div><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="اشرح بدقة ما الذي سيحدث ولماذا..." className="mt-3 min-h-[86px] w-full resize-none rounded-xl border border-input bg-background px-3 py-3 text-xs outline-none" data-testid="input-action-description" /><div className="mt-3 flex items-center justify-between gap-3"><p className="text-[11px] text-muted-foreground">لن يتم تنفيذ هذا الطلب تلقائياً.</p><button onClick={submit} disabled={!target.trim() || !description.trim() || createAction.isPending} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-bold text-primary-foreground disabled:opacity-50" data-testid="button-submit-connection-action">{createAction.isPending && <LoaderCircle size={14} className="animate-spin" />} إرسال للمراجعة</button></div></div>}
      <QueryState loading={connections.isLoading} error={connections.isError} onRetry={() => connections.refetch()}>
        <section><SectionLabel count={connectionList.length}>خريطة الاتصالات</SectionLabel>{connectionList.length ? <div className="grid gap-3 md:grid-cols-3">{connectionList.map((connection) => { const Icon = icons[connection.provider.toLowerCase()] ?? CloudCog; return <div key={connection.id} className="rounded-2xl border border-border bg-card p-5" data-testid={`connection-${connection.id}`}><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-xl bg-secondary"><Icon size={22} /></div><StatusPill status={connection.status} /></div><h3 className="mt-5 font-display text-lg font-bold capitalize">{connection.provider}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{connection.note}</p><div className="mt-5 flex flex-wrap gap-1.5 border-t border-border pt-4">{connection.capabilities.map((capability) => <span key={capability} className="rounded-md bg-muted px-2 py-1 font-mono text-[9px] text-muted-foreground ltr">{capability}</span>)}</div></div>; })}</div> : <EmptyState title="لا توجد اتصالات" detail="سيعرض النظام الخدمات عندما تصبح متاحة." />}</section>
      </QueryState>
      <section className="mt-8"><div className="mb-3 flex items-center justify-between"><SectionLabel count={actionList.length}>طلبات التغيير</SectionLabel><div className="flex items-center gap-2 text-[10px] text-muted-foreground"><ShieldAlert size={14} className="text-orange-600" /> التنفيذ يحتاج موافقة</div></div><QueryState loading={actions.isLoading} error={actions.isError} onRetry={() => actions.refetch()}>{actionList.length ? <div className="space-y-3">{actionList.map((item) => <div key={item.id} className="rounded-2xl border border-border bg-card p-4 sm:p-5" data-testid={`connection-action-${item.id}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex flex-1 items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-secondary text-muted-foreground"><GitBranch size={16} /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{item.action}</p><StatusPill status={item.status} /></div><p className="mt-1 font-mono text-[10px] text-muted-foreground"><span className="ltr">{item.provider} / {item.target}</span><span className="px-2">·</span>{formatDate(item.createdAt)}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{item.description}</p></div></div>{item.status.toLowerCase().includes('pending') && <div className="flex shrink-0 gap-2"><button onClick={() => approve.mutate({ id: item.id }, { onSuccess: refresh })} disabled={approve.isPending || reject.isPending} className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-[11px] font-bold text-primary-foreground disabled:opacity-50" data-testid={`button-approve-action-${item.id}`}><Check size={13} /> موافقة</button><button onClick={() => reject.mutate({ id: item.id }, { onSuccess: refresh })} disabled={approve.isPending || reject.isPending} className="flex items-center gap-1.5 rounded-lg border border-destructive/25 px-3 py-2 text-[11px] font-bold text-destructive disabled:opacity-50" data-testid={`button-reject-action-${item.id}`}><X size={13} /> رفض</button></div>}</div></div>)}</div> : <EmptyState title="لا توجد طلبات معلقة" detail="طلبات تغييرات GitHub وSupabase وCloudflare ستظهر هنا قبل تنفيذها." />}</QueryState></section>
    </div>
  </ConsoleShell>;
}